build nodejs docker container with all node stuff required to run the tests; deps cleanup

diff --git a/nodejs/Dockerfile b/nodejs/Dockerfile
--- a/nodejs/Dockerfile
+++ b/nodejs/Dockerfile
@@ -4,6 +4,28 @@ MAINTAINER riox
 ADD . /code
 WORKDIR /code
 
-RUN ./bin/bootstrap-node-reqs.sh
+# RUN ./bin/bootstrap-node-reqs.sh
+
+RUN rm -rf `find . -name node_modules`
+
+# install binaries: gulp, mocha
+RUN npm install -g gulp mocha
+RUN gulp -v || exit 1
+
+# install all deps required to make a gulp run
+RUN npm install --ignore-scripts
+
+# install bower dep
+RUN gulp ui:bower
+
+# now install all other modules (global flag on: -g)
+RUN gulp deps:install:global
+
+# install some commonly used tools inside the container
+RUN apt-get update -y
+RUN apt-get install -y vim nano less
+
+# clean up
+RUN rm -rf /code
 
 CMD ["/bin/bash"]
